require('../config/bootstrap');
require('dotenv').config({ path: require('path').resolve(__dirname, '../.env') });
const mongoose = require('mongoose');
const { connectDB, disconnectDB } = require('../config/db');
const MedicalShop = require('../models/MedicalShop');

const verifiedShops = [
  {
    name: 'Apollo Pharmacy 24x7',
    address: 'Block CF-332, Sector 1, Salt Lake',
    area: 'Salt Lake',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700064',
    landmark: 'Near CA Island',
    phone: '+91 98301 23456',
    alternatePhone: '033-2334-1122',
    is24x7: true,
    latitude: 22.5852,
    longitude: 88.4061,
    description: 'Fully stocked 24x7 emergency chemist with emergency refrigerated life-saving drugs, surgical disposables, and oxygen supplies.',
    services: ['24x7 Dispensing', 'Refrigerated Cold-Chain Drugs', 'Home Delivery', 'Emergency Oxygen Cylinders'],
    isActive: true,
  },
  {
    name: 'Frank Ross Pharmacy 24x7',
    address: '77A Park Street, Ground Floor',
    area: 'Park Street',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700016',
    landmark: 'Opposite Park Street Police Station',
    phone: '+91 98302 34567',
    alternatePhone: '033-2229-8800',
    is24x7: true,
    latitude: 22.5518,
    longitude: 88.3524,
    description: 'Premier heritage 24x7 pharmacy offering prescription medications, ICU critical care injections, and baby care essentials.',
    services: ['24x7 Dispensing', 'Cardiac & Critical Care Injections', 'Doctor On-Call', 'Wheelchair Assistance'],
    isActive: true,
  },
  {
    name: 'MedPlus 24x7 Pharmacy',
    address: '142 Rashbehari Avenue, Gariahat Crossing',
    area: 'Gariahat',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700029',
    landmark: 'Near Gariahat Flyover',
    phone: '+91 98303 45678',
    alternatePhone: '033-2464-9900',
    is24x7: true,
    latitude: 22.5198,
    longitude: 88.3685,
    description: 'Reliable 24x7 chain pharmacy with computerized billing, temperature-controlled insulin storage, and rapid emergency dispatch.',
    services: ['24x7 Dispensing', 'Insulin & Diabetic Care', 'Generic & Branded Medicines'],
    isActive: true,
  },
  {
    name: 'Dhanwantary 24x7 Medical Store',
    address: '124 Bidhan Sarani, Shyambazar 5-Point Crossing',
    area: 'Shyambazar',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700004',
    landmark: 'Near Netaji Statue',
    phone: '+91 98304 56789',
    alternatePhone: '033-2555-4321',
    is24x7: true,
    latitude: 22.6025,
    longitude: 88.3712,
    description: 'Key North Kolkata round-the-clock emergency medical supplier serving critical patients, trauma cases, and local nursing homes.',
    services: ['24x7 Dispensing', 'Surgical Implants & Orthopedic Support', 'Nebulizers & Inhalers'],
    isActive: true,
  },
  {
    name: 'S.S.K.M. Fair Price 24x7 Pharmacy',
    address: 'IPGMER & SSKM Hospital Campus, 244 AJC Bose Road',
    area: 'Bhowanipore',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700020',
    landmark: 'Inside SSKM Hospital Gate 1',
    phone: '+91 98305 67890',
    alternatePhone: '033-2223-1589',
    is24x7: true,
    latitude: 22.5394,
    longitude: 88.3435,
    description: 'Government subsidized round-the-clock fair-price medicine shop stocking oncology, cardiology, neurology, and trauma medications.',
    services: ['24x7 Fair Price Medicines', 'Government Subsidized', 'Critical Oncology & ICU Drugs'],
    isActive: true,
  },
  {
    name: 'Woodlands Hospital 24x7 Pharmacy',
    address: '8/5 Alipore Road, Woodlands Multispeciality Hospital',
    area: 'Alipore',
    city: 'Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    pincode: '700027',
    landmark: 'Near Alipore Zoo',
    phone: '+91 98306 78901',
    alternatePhone: '033-2456-7000',
    is24x7: true,
    latitude: 22.5326,
    longitude: 88.3301,
    description: 'In-house hospital pharmacy operating 24 hours open to both admitted inpatients and emergency outpatient citizens.',
    services: ['24x7 Dispensing', 'Hospital Inpatient & Outpatient', 'IV Fluids & Antibiotics'],
    isActive: true,
  },
  {
    name: 'Apollo Pharmacy 24x7 Howrah',
    address: '22 Station Road, Howrah Railway Station Complex',
    area: 'Howrah Station',
    city: 'Howrah',
    district: 'Howrah',
    state: 'West Bengal',
    pincode: '711101',
    landmark: 'Opposite Howrah Station Platform 1',
    phone: '+91 98307 89012',
    alternatePhone: '033-2638-7766',
    is24x7: true,
    latitude: 22.5841,
    longitude: 88.3412,
    description: 'Crucial 24x7 transit pharmacy serving travelers, local residents, and emergency railway medical transfers.',
    services: ['24x7 Dispensing', 'Emergency First Aid Kits', 'Travel Medicine'],
    isActive: true,
  },
  {
    name: 'MedPlus Shibpur 24x7',
    address: '89 Mandirtala, Vidyasagar Setu Toll Plaza Road',
    area: 'Shibpur',
    city: 'Howrah',
    district: 'Howrah',
    state: 'West Bengal',
    pincode: '711102',
    landmark: 'Near Nabanna State Secretariat',
    phone: '+91 98308 90123',
    alternatePhone: '033-2678-3344',
    is24x7: true,
    latitude: 22.5658,
    longitude: 88.3182,
    description: '24-hour retail pharmacy with full supply of pediatric, maternal, and elderly care prescriptions.',
    services: ['24x7 Dispensing', 'Pediatric Care', 'Home Delivery'],
    isActive: true,
  },
  {
    name: 'Frank Ross Pharmacy 24x7 Hooghly',
    address: '45 G.T. Road, Chinsurah Station More',
    area: 'Chinsurah',
    city: 'Chinsurah',
    district: 'Hooghly',
    state: 'West Bengal',
    pincode: '712101',
    landmark: 'Near Chinsurah Clock Tower',
    phone: '+91 98309 01234',
    alternatePhone: '033-2680-2211',
    is24x7: true,
    latitude: 22.9028,
    longitude: 88.3968,
    description: 'Primary 24x7 emergency medical hub in Hooghly district connected to nearby district hospitals and nursing facilities.',
    services: ['24x7 Dispensing', 'Critical Injectables', 'Blood Pressure & Sugar Check'],
    isActive: true,
  },
  {
    name: 'Serampore 24x7 Day-Night Chemist',
    address: '112 Mohanlal Saha Lane, Battala',
    area: 'Serampore',
    city: 'Serampore',
    district: 'Hooghly',
    state: 'West Bengal',
    pincode: '712201',
    landmark: 'Near Serampore Walsh Hospital',
    phone: '+91 98310 12345',
    alternatePhone: '033-2652-9988',
    is24x7: true,
    latitude: 22.7512,
    longitude: 88.3446,
    description: 'Community emergency pharmacy providing continuous service day and night directly adjacent to the Walsh Subdivisional Hospital.',
    services: ['24x7 Day & Night Service', 'Emergency Dressing Kits', 'Dialysis Disposables'],
    isActive: true,
  },
  {
    name: 'Bidhannagar 24x7 Emergency Chemist',
    address: 'Ultadanga VIP Road Crossing, P-23 CIT Scheme',
    area: 'Ultadanga',
    city: 'Kolkata',
    district: 'North 24 Parganas',
    state: 'West Bengal',
    pincode: '700054',
    landmark: 'Near Hudco Crossing',
    phone: '+91 98311 23456',
    alternatePhone: '033-2356-7890',
    is24x7: true,
    latitude: 22.5935,
    longitude: 88.3912,
    description: 'Strategic round-the-clock medical provider at the gateway connecting Kolkata and North 24 Parganas.',
    services: ['24x7 Dispensing', 'Nebulization Support', 'Oxygen Concentrator Rental'],
    isActive: true,
  },
  {
    name: 'Barasat 24x7 Medical Store',
    address: '56 Jessore Road, Colony More',
    area: 'Barasat',
    city: 'Barasat',
    district: 'North 24 Parganas',
    state: 'West Bengal',
    pincode: '700124',
    landmark: 'Near Barasat District Hospital',
    phone: '+91 98312 34567',
    alternatePhone: '033-2584-1234',
    is24x7: true,
    latitude: 22.7234,
    longitude: 88.4811,
    description: 'Largest 24x7 retail medical supplier in North 24 Parganas with immediate stock of venom antiserum, tetanus toxoids, and vaccines.',
    services: ['24x7 Emergency Drugs', 'Vaccines & Antivenom', 'Surgical Sutures'],
    isActive: true,
  },
  {
    name: 'Jadavpur 24x7 Medicine Centre',
    address: '92 Raja S.C. Mallick Road, 8B Bus Stand',
    area: 'Jadavpur',
    city: 'Kolkata',
    district: 'South 24 Parganas',
    state: 'West Bengal',
    pincode: '700032',
    landmark: 'Near Jadavpur University Gate 4',
    phone: '+91 98313 45678',
    alternatePhone: '033-2414-5566',
    is24x7: true,
    latitude: 22.4988,
    longitude: 88.3715,
    description: 'South Kolkata 24-hour pharmaceutical retailer serving students, local families, and nearby specialized oncology centers.',
    services: ['24x7 Dispensing', 'Cold-Chain Biologicals', 'Home Delivery'],
    isActive: true,
  },
  {
    name: 'Asansol 24x7 Medical Hall',
    address: '15 G.T. Road, Burnpur More',
    area: 'Asansol',
    city: 'Asansol',
    district: 'Paschim Bardhaman',
    state: 'West Bengal',
    pincode: '713301',
    landmark: 'Near Asansol District Hospital Gate',
    phone: '+91 98314 56789',
    alternatePhone: '0341-225-4433',
    is24x7: true,
    latitude: 23.6889,
    longitude: 86.9661,
    description: 'Key industrial belt 24x7 pharmacy with specialized burn, trauma, and respiratory emergency supplies.',
    services: ['24x7 Emergency Chemist', 'Burn & Trauma Dressings', 'Industrial First Aid'],
    isActive: true,
  },
  {
    name: 'Durgapur City Center 24x7 Pharmacy',
    address: 'Plot 4A, Commercial Zone, City Center',
    area: 'City Center',
    city: 'Durgapur',
    district: 'Paschim Bardhaman',
    state: 'West Bengal',
    pincode: '713216',
    landmark: 'Beside Junction Mall',
    phone: '+91 98315 67890',
    alternatePhone: '0343-254-8899',
    is24x7: true,
    latitude: 23.5350,
    longitude: 87.2980,
    description: 'Modern 24x7 medicine supermarket stocking over 10,000 branded formulations and orthopedic emergency equipment.',
    services: ['24x7 Dispensing', 'Orthopedic Braces', 'Baby Care & Nutrition'],
    isActive: true,
  },
  {
    name: 'Siliguri 24x7 Emergency Chemist',
    address: '88 Sevoke Road, Panitanki More',
    area: 'Sevoke Road',
    city: 'Siliguri',
    district: 'Darjeeling',
    state: 'West Bengal',
    pincode: '734001',
    landmark: 'Opposite Panitanki Traffic Point',
    phone: '+91 98316 78901',
    alternatePhone: '0353-253-1122',
    is24x7: true,
    latitude: 26.7271,
    longitude: 88.4316,
    description: 'North Bengal regional 24-hour pharmaceutical lifeline catering to Siliguri, Darjeeling hills, and neighboring transit corridors.',
    services: ['24x7 Dispensing', 'High Altitude Sickness Medicines', 'Emergency Injectables'],
    isActive: true,
  },
];

async function seedMedicalShops() {
  try {
    await connectDB();
    console.log('📡 Connected to MongoDB database for Medical Shop seeding.');

    for (const shopData of verifiedShops) {
      await MedicalShop.findOneAndUpdate(
        {
          name: shopData.name,
          district: shopData.district,
        },
        shopData,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }

    const count = await MedicalShop.countDocuments();
    console.log(`✅ Successfully seeded verified 24x7 Medical Shops! Total active records: ${count}`);
    await disconnectDB();
  } catch (err) {
    console.error('❌ Error seeding medical shops:', err);
    process.exit(1);
  }
}

if (require.main === module) {
  seedMedicalShops();
}

module.exports = { seedMedicalShops, verifiedShops };
